### ISSUE TITLE
Distribute tests and license

### ISSUE THREAD

**Issue by FRidh** [rca/cmdline#1]
Please distribute tests and the license when releasing on PyPI. The last release includes neither and both are very useful for distribution packagers. Thanks!

**Comment by rca** [comment]
Thanks for the suggestion; I will do so on the next push.

**Comment by rca** [comment]
Hey @FRidh, I started looking at this and need some help.

With respect to `LICENSE` [it's listed in setup.py](https://github.com/rca/cmdline/blob/master/setup.py#L20).  Is there something else I need to do in order to incorporate it into the package?

And for tests, I'm not sure how to go about properly integrating them.

Can you provide me with a reference example for each of these.

Thanks!

**Comment by FRidh** [comment]
Hi @rca, great that you're having a look at it.

### License

Regarding the license I recommend using a [classifier](https://pypi.python.org/pypi?%3Aaction=list_classifiers). If your license isn't mentioned in the list, you can use the license field (which you currently use) and give either the name of the `license` or the file (which you did now).
In any case, you can include the license in the distribution by adding it to your `MANIFEST.in`.

### Root folder

Furthermore, with Python packages it is a convention to put the Python files in a folder that has the same name as the package, in this case `cmdline` instead of `src`.

### Tests

You can choose to put the folder `tests` in the root of your repo (this is often done) or you put them in `cmdline` (also often done). You will have to make sure they're included in the archive.

```
from setuptools import find_packages
packages=find_packages(),
```

If you've renamed `src` to `cmdline` you can drop `package_dir`.

### Example project

I think [Blaze](https://github.com/blaze/blaze) would be a good example of how to write a `setup.py` and organize the files.

**Comment by rca** [comment]
Should be resolved in master
